### PR TITLE
Optimize raw_next

### PR DESCRIPTION
**Pull request by ltheinrich**
Increase i in for loop only if required

### CODE REVIEW

**Comment by deeprobin** [comment]
Thank you for that pull request. I'll do tomorrow some checks. 
Some people said String::new is const, some people said String::default does not allocate.

**Comment by ltheinrich** [comment]
String::default returns String:new, so it's the same. Both don't allocate at first.

**Comment by deeprobin** [comment]
I'm sorry but there was a pull request with an better solution. You're welcome to find more improvements.

Thank you for your engagement.

**Comment by deeprobin** [comment]
Can improve your improvement, so that I could merge it?

**Comment by ltheinrich** [comment]
You can merge already.

**Comment by deeprobin** [comment]
That's perfect ❤️.
Merged.

**Pull request merged**
